#!/usr/bin/env ruby

require "optparse"
require "socket"

def host_addr
  Socket.getifaddrs.
         find {|f| f.name == "docker0" and f.addr.ip? and f.addr.ipv6? == false }.
         addr.ip_address
end

dns_servers = "1.1.1.1"
share_x11 = false
share_downloads = true
shared_downloads_path = "/tmp/firefox-downloads"
shm_size = "2g"
profile_path = nil
profile_name = nil
volumes = []
env_vars = []
image_name = "firefox"

OptionParser.new do |opts|
  opts.on "-x", "--[no-]share-x11", "Share X11 instance" do |v|
    share_x11 = v
  end

  opts.on "-v", "--volume [VOLUME]", "Add more volumes to the container" do |v|
    volumes << v
  end

  opts.on "-e", "--env [VOLUME]", "Add more enviroment variables to the container" do |v|
    env_vars << v
  end

  opts.on "-d", "--disable-share-downloads", "Disable shared downloads path" do |v|
    share_downloads = !v
  end

  opts.on "-i", "--image [IMAGE]", "Docker image" do |v|
    image_name = v
  end

  opts.on "-pPROFILE", "--profile=PATH", "Profile path" do |name|
    if name !~ /\A(\w|-)+\Z/
      STDERR.puts "Invalid profile name: #{name}"
      exit 1
    end
    profile_name = name
    profile_path = File.expand_path("~/.config/docker-firefox/profiles/#{name}")
  end

  opts.on "-DPATH", "--downloads=PATH", "Path shared by downloads" do |v|
    shared_downloads_path = v
  end

  opts.on "-s", "--shm-size", "Set the size of /dev/shm of the container" do |v|
    shm_size = v
  end

  opts.on "-DDNS", "--dns=DNS", "DNS servers" do |d|
    dns_servers = d
  end
end.parse!

if not profile_path
  profile_name = "tmp-" + Time.now.strftime("%Y%m%d%H%M%S")
  profile_path = "/tmp/.docker-firefox/profiles/#{profile_name}"
end

container_name = "firefox-#{profile_name}"

puts "Container Name: \033[1m#{container_name}\033[m"

cmd = [ "docker", "run", "--name", container_name ]

# See https://github.com/jlesage/docker-firefox#increasing-shared-memory-size

cmd << "--shm-size" << shm_size

cmd << "--dns" << dns_servers

if share_x11
  if xdg_rt = ENV["XDG_RUNTIME_DIR"]
    cmd << "-e" << "XDG_RUNTIME_DIR=#{xdg_rt}"
    cmd << "-v" << "#{xdg_rt}:#{xdg_rt}"
  end

  if wl_display = ENV["WAYLAND_DISPLAY"]
    cmd << "--rm"
    cmd << "-e" << "MOZ_ENABLE_WAYLAND=1"
    cmd << "-e" << "WAYLAND_DISPLAY=#{wl_display}"
  else
    cmd.concat %w(--rm -v /tmp/.X11-unix/:/tmp/.X11-unix -e)
    cmd << "DISPLAY=#{ENV["DISPLAY"]}"
  end
else
  cmd << "-d" << "-e" << "DISPLAY=:0"
end

if share_downloads
  if not File.directory?(shared_downloads_path)
    Dir.mkdir shared_downloads_path
  end

  cmd << "-v" << "#{shared_downloads_path}:/browser/Downloads"
  STDERR.puts "[INFO] Shared downloads in #{shared_downloads_path}"
end

if not File.directory?(profile_path)
  system "mkdir", "-p", profile_path
end

cmd << "-v" << "#{profile_path}:/browser"
STDERR.puts "[INFO] Profile in #{profile_path}"

env_vars.each do |env|
  cmd << "-e" << env
end

volumes.each do |vol|
  cmd << "-v" << vol
end

cmd << image_name

if share_x11
  cmd.concat %w(firefox --new-instance --Private)
else
  cmd << "/usr/local/bin/browsersystem"
end

puts "[INFO] #{cmd.join(" ")}"

output_log = "/tmp/.firefox-#{container_name}"

if fork
  STDERR.puts "Log to #{output_log}"
  exit
end

STDIN.reopen("/dev/null", "r")
STDOUT.reopen(output_log, "a")
STDERR.reopen(output_log, "a")

if share_x11

  exec(*cmd)

else

  cid = IO.popen(cmd).read.strip
  ip_address = IO.popen(["docker", "inspect",  "-f", "{{.NetworkSettings.IPAddress}}", cid]).read.strip
  puts "[INFO] Container #{cid} @ #{ip_address}"

  vnc_pid = fork do
    n = 0
    while n < 1000
      begin
        TCPSocket.new(ip_address, 5900).close
        break
      rescue Errno::ECONNREFUSED
        STDERR.print "\rWait VNC (#{n})\033[K"
        STDERR.flush
        sleep 0.1
        n += 1
        retry
      end
    end

    exec "gvncviewer", ip_address
  end

  system "docker", "wait", cid
  system "docker", "rm", cid
  Process.waitpid(vnc_pid)

end
