pref("accessibility.typeaheadfind.flashBar", 0);
pref("accessibility.warn_on_browsewithcaret", false);
// pref("browser.display.use_document_fonts", 0);
pref("browser.reader.detectedFirstArticle", true);
pref("browser.rights.3.shown", true);
pref("browser.search.countryCode", "US");
pref("browser.search.region", "US");
pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1400000000000");
pref("full-screen-api.pointer-lock.enabled", false);
pref("full-screen-api.transition-duration.enter", "15 20");
pref("full-screen-api.transition-duration.leave", "15 20");
pref("full-screen-api.transition.timeout", 100);
pref("full-screen-api.warning.delay", 0);
pref("full-screen-api.warning.timeout", 500);
pref("general.smoothScroll", false);
pref("general.warnOnAboutConfig", false);
pref("view_source.wrap_long_lines", true);
pref("browser.pocket.enabled", false);
pref("browser.safebrowsing.downloads.enabled", false);
pref("browser.safebrowsing.malware.enabled", false);
pref("browser.safebrowsing.enabled", false);
pref("browser.urlbar.trimURLs", false);
pref("browser.zoom.siteSpecific", false);
pref("device.sensors.enabled", false);
pref("dom.battery.enabled", false);
pref("dom.event.clipboardevents.enabled", false);
pref("geo.enabled", false);
pref("media.eme.enabled", false);
pref("privacy.donottrackheader.enabled", true);
pref("privacy.trackingprotection.enabled", true);
pref("social.whitelist", "");
pref("social.remote-install.enabled", false);
pref("social.toast-notifications.enabled", false);
pref("webgl.disabled", true);
