#!/bin/bash

set -e

export DISPLAY=:0

Xtigervnc :0 -screen 0 1200x800x24 -ac SecurityTypes=None &
XSERVER=$!

sleep 1
ratpoison &

echo -e '\e[1mAddress:\e[m'
ip addr show eth0 | grep inet

/opt/firefox/firefox --Private --new-instance

kill -9 $XSERVER
wait
wait
